# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.29

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1384/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1384/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/haleen/os/idz3

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/haleen/os/idz3

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/snap/cmake/1384/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1384/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haleen/os/idz3/CMakeFiles /home/haleen/os/idz3//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/haleen/os/idz3/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 4-5_s

# Build rule for target.
4-5_s: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 4-5_s
.PHONY : 4-5_s

# fast build rule for target.
4-5_s/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_s.dir/build.make CMakeFiles/4-5_s.dir/build
.PHONY : 4-5_s/fast

#=============================================================================
# Target rules for targets named 4-5_c

# Build rule for target.
4-5_c: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 4-5_c
.PHONY : 4-5_c

# fast build rule for target.
4-5_c/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_c.dir/build.make CMakeFiles/4-5_c.dir/build
.PHONY : 4-5_c/fast

4-5/client.o: 4-5/client.cpp.o
.PHONY : 4-5/client.o

# target to build an object file
4-5/client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_c.dir/build.make CMakeFiles/4-5_c.dir/4-5/client.cpp.o
.PHONY : 4-5/client.cpp.o

4-5/client.i: 4-5/client.cpp.i
.PHONY : 4-5/client.i

# target to preprocess a source file
4-5/client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_c.dir/build.make CMakeFiles/4-5_c.dir/4-5/client.cpp.i
.PHONY : 4-5/client.cpp.i

4-5/client.s: 4-5/client.cpp.s
.PHONY : 4-5/client.s

# target to generate assembly for a file
4-5/client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_c.dir/build.make CMakeFiles/4-5_c.dir/4-5/client.cpp.s
.PHONY : 4-5/client.cpp.s

4-5/server.o: 4-5/server.cpp.o
.PHONY : 4-5/server.o

# target to build an object file
4-5/server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_s.dir/build.make CMakeFiles/4-5_s.dir/4-5/server.cpp.o
.PHONY : 4-5/server.cpp.o

4-5/server.i: 4-5/server.cpp.i
.PHONY : 4-5/server.i

# target to preprocess a source file
4-5/server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_s.dir/build.make CMakeFiles/4-5_s.dir/4-5/server.cpp.i
.PHONY : 4-5/server.cpp.i

4-5/server.s: 4-5/server.cpp.s
.PHONY : 4-5/server.s

# target to generate assembly for a file
4-5/server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_s.dir/build.make CMakeFiles/4-5_s.dir/4-5/server.cpp.s
.PHONY : 4-5/server.cpp.s

lib.o: lib.cpp.o
.PHONY : lib.o

# target to build an object file
lib.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_s.dir/build.make CMakeFiles/4-5_s.dir/lib.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_c.dir/build.make CMakeFiles/4-5_c.dir/lib.cpp.o
.PHONY : lib.cpp.o

lib.i: lib.cpp.i
.PHONY : lib.i

# target to preprocess a source file
lib.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_s.dir/build.make CMakeFiles/4-5_s.dir/lib.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_c.dir/build.make CMakeFiles/4-5_c.dir/lib.cpp.i
.PHONY : lib.cpp.i

lib.s: lib.cpp.s
.PHONY : lib.s

# target to generate assembly for a file
lib.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_s.dir/build.make CMakeFiles/4-5_s.dir/lib.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/4-5_c.dir/build.make CMakeFiles/4-5_c.dir/lib.cpp.s
.PHONY : lib.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... 4-5_c"
	@echo "... 4-5_s"
	@echo "... 4-5/client.o"
	@echo "... 4-5/client.i"
	@echo "... 4-5/client.s"
	@echo "... 4-5/server.o"
	@echo "... 4-5/server.i"
	@echo "... 4-5/server.s"
	@echo "... lib.o"
	@echo "... lib.i"
	@echo "... lib.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

